### ISSUE TITLE
Make stable cascade the default

### ISSUE THREAD

**Issue by db0** [RikudouSage/HordeNG#2]
vanilla Stable diffusion 1.5 is way too old and someone would get the wrong idea of the capabilities of the website if it's the first they use. Suggested you switch to using Stable Cascade as the default, or alternatively a generalist SDXL model you might prefer, like Albedo

**Comment by RikudouSage** [comment]
Stable Cascade always generates white blank images for me. And the few times it didn't it triggered the CSAM filter. But Albedo sounds reasonable.

**Comment by RikudouSage** [comment]
Done.

**Comment by db0** [comment]
> Stable Cascade always generates white blank images for me. And the few times it didn't it triggered the CSAM filter. But Albedo sounds reasonable.

That's very strange. Did you make sure you generated using 1024x1024? It (and SDXL models) don't work well in 512x512
